### ISSUE TITLE
New flow with "If..." card OpenAI selected causes crash: "TypeError: Cannot read property 'length' of null"

### ISSUE THREAD

**Issue by alwa** [frodeheg/OpenAI#7]
Steps to reproduce:
- Start Homey
- Add new flow
- Select "If..." and the app OpenAI

Expected: Works

Actual: Crash ("TypeError: Cannot read property 'length' of null")

Context:
- Homey Pro (Early 2023)
- Homey Android App
- Version: 1.4.0 of this app

Is this a missing feature? (https://github.com/frodeheg/OpenAI/issues/3)

**Comment by frodeheg** [comment]
Thank you for the report.
I can reproduce it. (as well as for some other apps)

The reason I have not seen this is because 
1) This problem does not occur when you use advanced flows.
2) It did not occur previously
3) This is completely disconnected to the app itself (no app-specific flow should be run when listing if-cards for an app)

Thus, I wonder if this is a bug introduced by Athom.

I will do some investigation, but I have no clue how this can be caused by the app itself.

**Comment by frodeheg** [comment]
I found out that the problem only occurs in the Android app.
If you use the same procedure in the web interface (my.homey.app) then it does not crash. Neither does it crash using advanced flows.... I have posted a question on slack to see if this is a known bug with the Android app.
